"""
data.py — All 52 Provincias with REAL tramites from cita previa website
Tramites extracted from Chrome extension cita-bot-v32 (real icp.administracionelectronica.gob.es data)
"""

# ── Real tramite names as shown on website ────────────────────────────────────
HUELLAS       = 'POLICÍA-TOMA DE HUELLAS (EXPEDICIÓN DE TARJETA) INICIAL, RENOVACIÓN, DUPLICADO Y LEY 14/2013'
TIE           = 'POLICIA - RECOGIDA DE TARJETA DE IDENTIDAD DE EXTRANJERO (TIE)'
TIE_DGM       = 'POLICÍA-RECOGIDA DE LA TIE CUYA AUTORIZACIÓN RESUELVE LA DIRECCIÓN GENERAL DE GESTIÓN MIGRATORIA'
NIE           = 'POLICIA-ASIGNACIÓN DE NIE'
ASIGNACION_NIE= 'Asignación de N.I.E.'
CERT_RESIDENTE= 'Certificado de residente o no residente'
CERTS_UE_PLAIN= 'CERTIFICADOS UE'
CARTA         = 'POLICIA-CARTA DE INVITACIÓN'
CERT_UE       = 'POLICIA-CERTIFICADO DE REGISTRO DE CIUDADANO DE LA U.E.'
CERTS         = 'POLICIA-CERTIFICADOS (DE RESIDENCIA, DE NO RESIDENCIA Y DE CONCORDANCIA)'
CERTS_NIE     = 'POLICIA-CERTIFICADOS Y ASIGNACION NIE'
CERTS_NIE_NC  = 'POLICIA-CERTIFICADOS Y ASIGNACION NIE (NO COMUNITARIOS)'
CEDULA        = 'POLICÍA - CÉDULA DE INSCRIPCIÓN'
PRORROGA      = 'POLICÍA-PRORROGA DE ESTANCIA'
TARJ_ROJA     = 'POLICÍA-RECOGIDA DE TARJETA ROJA (PROTECCIÓN INTERNACIONAL)'
SOL_TARJ_ROJA = 'POLICÍA-SOLICITUD TARJETA ROJA'
DOC_ROJA      = 'Policía-Documento acreditativo solicitante,en tramitación,de protección internacional (tarjeta roja)'
BREXIT        = 'POLICÍA-EXP.TARJETA ASOCIADA AL ACUERDO DE RETIRADA CIUDADANOS BRITÁNICOS Y SUS FAMILIARES (BREXIT)'
TARJ_DGM      = 'POLICÍA-EXPEDICIÓN DE TARJETAS CUYA AUTORIZACIÓN RESUELVE LA DIRECCIÓN GENERAL DE GESTIÓN MIGRATORIA'
APATRIDIA     = 'POLICÍA-EXPEDICIÓN/RENOVACIÓN DE DOCUMENTOS DE SOLICITUD DE APATRIDIA'
EXP_CARTA_INV = 'Expedición de Carta de Invitación'
UCRANIA       = 'POLICÍA TARJETA CONFLICTO UCRANIA–ПОЛІЦІЯ -КАРТКА ДЛЯ ПЕРЕМІЩЕНИХ ОСІБ ВНАСЛІДОК КОНФЛІКТУ В УКРАЇНІ'
UCRANIA_SOL   = 'POLICÍA - UCRANIA : SOLICITUD PROTECCIÓN TEMPORAL DESPLAZADOS'
AUTOREG       = 'POLICIA-AUTORIZACIÓN DE REGRESO'
RECOG_CERT    = 'POLICÍA-RECOGIDA CERTIFICADO Y AUTORIZACIÓN DE REGRESO'
INFO          = 'POLICIA-INFORMACION DE TRÁMITES DE LA COMISARÍA DE POLICIA'
ASILO_SOL     = 'POLICIA- SOLICITUD ASILO'
ASILO_EXP     = 'POLICIA- EXPEDICIÓN/RENOVACIÓN DE DOCUMENTOS DE SOLICITANTES DE ASILO'
ASILO_INFO    = 'POLICIA-ASILO INFORMACION'
ASILO_MADRID  = 'ASILO - PRIMERA CITA-provincia de Madrid'
OTROS         = 'POLICIA - OTROS TRÁMITES COMISARIA'
CAMBIO_DOM    = 'POLICIA - COMUNICACIÓN DE CAMBIO DE DOMICILIO'
TITULOS       = 'POLICÍA - TÍTULOS DE VIAJE'
SOL_APATRIDA  = 'POLICÍA - SOLICITUD DE APATRIDA'
CERT_CONC     = 'POLICIA - CERTIFICADOS CONCORDANCIA'
NIE_NO_RES    = 'POLICÍA-ASIGNACIÓN NIE NO RESIDENTE NO COMUNITARIO'
CERTS_RES_CONC= 'POLICÍA-CERTIFICADOS (RESIDENCIA Y CONCORDANCIA)'
POL_ASILO_SOL = 'POLICÍA-SOLICITUD ASILO'
CERT_NIE      = 'POLICIA-CERTIFICADOS Y ASIGNACION NIE'
CERT_NIE_NC   = 'POLICIA-CERTIFICADOS Y ASIGNACION NIE (NO COMUNITARIOS)'
CONSULTA_NIE  = 'POLICÍA-CONSULTA N.º DE NIE ASIGNADO'
DECL_ENTRADA  = 'POLICÍA-DECLARACIÓN DE ENTRADA'
PRORROGA_CON  = 'POLICÍA - PRORROGA DE ESTANCIA CON VISADO'
PRORROGA_SIN  = 'POLICÍA - PRORROGA DE ESTANCIA SIN VISADO'

# Extranjeria
EX_ARRAIGO    = 'AUT. DE RESIDENCIA TEMPORAL POR CIRCUNS. EXCEPCIONALES POR ARRAIGO'
EX_ARRAIGO2   = 'AUTORIZACIONES DE RESIDENCIA TEMPORAL POR MOTIVOS DE ARRAIGO Y OTRAS CIRCUNSTANCIAS EXCEPCIONALES'
EX_TRABAJO_EST= 'AUTORIZACIONES DE TRABAJO POR ESTUDIOS'
EX_FAM_UE     = 'AUTORIZACIONES DE RESIDENCIA TEMPORAL Y PERMANENTE DE FAMILIAR DE CIUDADANO DE LA UNION EUROPEA'
EX_TRABAJO    = 'AUTORIZACIONES DE TRABAJO, RENOVACIONES, PRÓRROGAS Y MODIFICACIONES'
EX_AUTOREG    = 'AUTORIZACIÓN DE REGRESO'
EX_MEN_ESP    = 'AUTORIZACIÓN DE RESIDENCIA DE MENORES O INCAPACITADOS NACIDOS EN ESPAÑA'
EX_MEN_NOESP  = 'AUTORIZACIÓN DE RESIDENCIA DE MENORES O INCAPACITADOS NO NACIDOS EN ESPAÑA'
EX_FAM_REAG   = 'AUTORIZACIÓN DE RESIDENCIA TEMPORAL POR REAGRUPACIÓN FAMILIAR'
EX_ESTUDIO    = 'ESTANCIA POR ESTUDIOS'
EX_FAM_COM    = 'FAMILIARES DE RESIDENTES COMUNITARIOS'
EX_INFO       = 'INFORMACIÓN'
EX_MOD        = 'MODIFICACIÓN de las SITUACIONES (sujeto legitimado EXTRANJERO)'
EX_REAG       = 'REAGRUPACIÓN FAMILIAR'
EX_REG        = 'REGISTRO'
EX_RENOV      = 'RENOVACIONES DE AUT. DE RESIDENCIA y/o AUT. DE RESIDENCIA Y TRABAJO'
EX_RENOV2     = 'RENOVACIONES DE RESIDENCIA'
EX_RENOV_REAG = 'RENOVACIÓN AUTORIZACIÓN RESIDENCIA POR REAGRUPACIÓN FAMILIAR'
EX_LARGA      = 'Recuperación de la autorización de larga duración'
EX_RENOVPP    = 'Renovaciones, Prórrogas y Modificaciones'
EX_RENOV_O_MOD= 'RENOVACIONES, PRÓRROGAS O MODIFICACIONES'
EX_FAM_ESP    = 'RESIDENCIA TEMPORAL DE FAMILIARES DE PERSONAS CON NACIONALIDAD ESPAÑOLA'
EX_LARGA_ACC  = 'ACCESO A 1ª AUT. DE RESIDENCIA DE LARGA DURACIÓN Y LARGA DURACIÓN UE'
EX_SOL_INIC   = 'SOLICITUD DE AUTORIZACIONES INICIALES'
EX_SOL        = 'SOLICITUD DE AUTORIZACIONES'
EX_IBIZA_INFO = 'INFORMACIÓN GENERAL - IBIZA'
EX_IBIZA_RENOV= 'RENOVACIONES, PRÓRROGAS Y MODIFICACIONES'
EX_IBIZA_SOL  = 'SOLICITUD AUTORIZACIONES - IBIZA'
EX_MALL_SOL   = 'SOLICITUD AUTORIZACIONES - MALLORCA'
EX_ASIG_NIE   = 'ASIGNACION NIE CIUDADANOS COMUNITARIOS'
REG           = 'AUTORIZACIONES EXTRAORDINARIAS: RESIDENCIA CIR. EXC. POR RAZÓN DE ARRAIGO Y ARRAIGO EXTRAORDINARIO'

# Common sets
POL_COMUN = [HUELLAS, TIE, NIE, CARTA, CERT_UE, CERTS, CEDULA, UCRANIA, DOC_ROJA, BREXIT, TARJ_DGM, PRORROGA, TIE_DGM, APATRIDIA, AUTOREG, INFO]
EX_COMUN  = [EX_ARRAIGO, EX_FAM_UE, EX_TRABAJO, EX_AUTOREG, EX_FAM_REAG, EX_INFO, EX_MOD, EX_REAG, EX_RENOV, EX_RENOV_REAG, EX_FAM_ESP, EX_SOL_INIC]

PROVINCIA_DATA = {
  "15": {
    "name": "A Coruña",
    "tramites": [TIE, ASILO_EXP, ASILO_SOL, NIE, ASILO_INFO, AUTOREG, CARTA, CERT_UE, CERTS, CERTS_NIE, CERTS_NIE_NC, UCRANIA, HUELLAS,
                 EX_LARGA_ACC, EX_ARRAIGO, EX_TRABAJO_EST, EX_ESTUDIO, EX_FAM_COM, EX_INFO, EX_REAG, EX_RENOV, EX_RENOV_REAG, EX_FAM_ESP],
    "oficinas": ["CNP - COMISARIA A CORUÑA - C/ RAMON Y CAJAL 4","CNP - COMISARIA FERROL - C/ DOLORES 1","CNP - COMISARIA SANTIAGO DE COMPOSTELA - C/ HORREO 4"]
  },
  "2": {
    "name": "Albacete",
    "tramites": [CERT_CONC, TIE, TITULOS, ASILO_EXP, CARTA, CERTS_NIE_NC, INFO, CEDULA, SOL_APATRIDA, UCRANIA_SOL, UCRANIA, APATRIDIA, TARJ_ROJA, POL_ASILO_SOL, HUELLAS, REG],
    "oficinas": ["CNP - COMISARIA ALBACETE - C/ TEODORO CAMINO 5","CNP - COMISARIA HELLIN - C/ CASTILLA LA MANCHA 2"]
  },
  "3": {
    "name": "Alicante",
    "tramites": [ASIGNACION_NIE, CERT_RESIDENTE, CERTS_UE_PLAIN, CERT_CONC, TIE, ASILO_EXP, ASILO_SOL, CARTA, CERT_UE, UCRANIA_SOL, UCRANIA, HUELLAS,
                 EX_FAM_UE, EX_ARRAIGO2, EX_TRABAJO, EX_AUTOREG, EX_MEN_ESP, EX_MEN_NOESP, EX_FAM_REAG, EX_ESTUDIO, EX_INFO, EX_MOD, EX_LARGA, EX_REG, EX_RENOV2, EX_RENOVPP, EX_FAM_ESP, REG],
    "oficinas": ["CNP - COMISARIA ALICANTE CENTRO - C/ MEDICO PASCUAL PEREZ 37","CNP - COMISARIA BENIDORM - C/ LLUIS SITGES 3","CNP - COMISARIA DENIA - C/ DIANA 14","CNP - COMISARIA ELCHE - C/ CORREGIDOR JOAQUIN MENDUIÑA 30","CNP - COMISARIA ELDA - C/ OSCAR ESPLA 15","CNP - COMISARIA ORIHUELA - C/ JOSE ANTONIO 2","CNP - COMISARIA TORREVIEJA - AV. DR. GREGORIO MARAÑON 22","CNP - COMISARIA VILLENA - AV. DE LA CONSTITUCION 50"]
  },
  "4": {
    "name": "Almería",
    "tramites": [TIE, ASILO_EXP, ASILO_SOL, NIE, CARTA, CERT_UE, CERTS, UCRANIA, HUELLAS, EX_ARRAIGO, EX_FAM_COM, REG],
    "oficinas": ["CNP - COMISARIA ALMERIA CENTRO - C/ CASTRO 4","CNP - COMISARIA EL EJIDO - C/ BENITAGLA 4","CNP - COMISARIA ROQUETAS DE MAR - C/ JOSE MANZANO 2"]
  },
  "1": {
    "name": "Álava / Araba",
    "tramites": [OTROS, TIE, ASILO_SOL, CARTA, SOL_APATRIDA, UCRANIA_SOL, UCRANIA, HUELLAS, EX_INFO, EX_SOL_INIC, REG],
    "oficinas": ["CNP - COMISARIA VITORIA-GASTEIZ - C/ JOSE LUIS IÑARRA 4"]
  },
  "33": {
    "name": "Asturias",
    "tramites": [CAMBIO_DOM, TIE, TITULOS, ASILO_EXP, ASILO_SOL, AUTOREG, CARTA, CERT_UE, CERTS, CERTS_NIE, INFO, CEDULA, UCRANIA, PRORROGA, HUELLAS,
                 EX_ARRAIGO, EX_FAM_COM, EX_INFO, EX_SOL, REG],
    "oficinas": ["CNP - COMISARIA AVILES - C/ LA MURALLA 4","CNP - COMISARIA GIJON - C/ RODRIGUEZ SAN PEDRO 2","CNP - COMISARIA LANGREO - C/ LLARANES 7","CNP - COMISARIA OVIEDO - C/ GENERAL ELORZA 32"]
  },
  "5": {
    "name": "Ávila",
    "tramites": [CAMBIO_DOM, TIE, TITULOS, ASILO_EXP, ASILO_SOL, CARTA, CERT_UE, CERTS_NIE, INFO, CEDULA, SOL_APATRIDA, UCRANIA_SOL, UCRANIA, HUELLAS, EX_SOL, REG],
    "oficinas": ["CNP - COMISARIA AVILA - C/ DUQUE DE ALBA 2"]
  },
  "6": {
    "name": "Badajoz",
    "tramites": [TIE, TITULOS, ASILO_EXP, ASILO_SOL, ASILO_INFO, CARTA, CERT_UE, CERTS_NIE, INFO, CEDULA, UCRANIA, PRORROGA, RECOG_CERT, TARJ_ROJA, HUELLAS, EX_INFO, EX_SOL, REG],
    "oficinas": ["CNP - COMISARIA BADAJOZ - C/ RAFAEL LUCENQUI 5","CNP - COMISARIA DON BENITO - AV. VILLANUEVA 2","CNP - COMISARIA MERIDA - C/ SAGASTA 15"]
  },
  "8": {
    "name": "Barcelona",
    "tramites": [EX_AUTOREG, CERT_CONC, TIE, TITULOS, ASILO_EXP, NIE, CARTA, CERT_UE, CERTS, CERTS_NIE, CERTS_NIE_NC, UCRANIA, NIE_NO_RES, CERTS_RES_CONC, BREXIT, TARJ_DGM, HUELLAS, REG],
    "oficinas": ["CNP - COMISARIA BADALONA - AVDA. DELS VENTS 9","CNP - COMISARIA CASTELLDEFELS - PLAÇA DE L'ESPERANTO 4","CNP - COMISARIA CERDANYOLA DEL VALLES - VERGE DE LES FEIXES 4","CNP - COMISARIA CORNELLA DE LLOBREGAT - AV. SANT ILDEFONS S/N","CNP - COMISARIA EL PRAT DE LLOBREGAT - CENTRE 4","CNP - COMISARIA GRANOLLERS - RICOMA 65","CNP - COMISARIA IGUALADA - PRAT DE LA RIBA 13","CNP - COMISARIA L'HOSPITALET DE LLOBREGAT - Rbla. Just Oliveres 43","CNP - COMISARIA MANRESA - SOLER I MARCH 5","CNP - COMISARIA MATARO - AV. GATASSA 15","CNP - COMISARIA MONTCADA I REIXAC - MAJOR 38","CNP - COMISARIA RIPOLLET - TAMARIT 78","CNP - COMISARIA RUBI - TERRASSA 16","CNP - COMISARIA SABADELL - BATLLEVELL 115","CNP - COMISARIA SANT ADRIA DEL BESOS - AV. JOAN XXIII 2","CNP - COMISARIA SANT BOI DE LLOBREGAT - RIERA BASTE 43","CNP - COMISARIA SANT CUGAT DEL VALLES - VALLES 1","CNP - COMISARIA SANT FELIU DE LLOBREGAT - CARRERETES 9","CNP - COMISARIA SANTA COLOMA DE GRAMENET - IRLANDA 67","CNP - COMISARIA TERRASSA - BALDRICH 13","CNP - COMISARIA VIC - BISBE MORGADES 4","CNP - COMISARIA VILADECANS - AVDA. BALLESTER 2","CNP - COMISARIA VILAFRANCA DEL PENEDES - AV. RONDA DEL MAR 109","CNP - COMISARIA VILANOVA I LA GELTRU - VAPOR 19","CNP MALLORCA-GRANADOS - MALLORCA 213","CNP - RAMBLA GUIPUSCOA 74"]
  },
  "48": {
    "name": "Bizkaia",
    "tramites": [EXP_CARTA_INV, TIE, TITULOS, ASILO_EXP, ASILO_SOL, NIE, AUTOREG, CERT_UE, CERTS, UCRANIA_SOL, UCRANIA, APATRIDIA, HUELLAS, EX_RENOV_O_MOD, EX_SOL_INIC, REG],
    "oficinas": ["CNP - COMISARIA BARAKALDO - C/ BUEN PASTOR 1","CNP - COMISARIA BASAURI - C/ ARIZ 30","CNP - COMISARIA BILBAO CENTRO - C/ LUIS BRIÑAS 14","CNP - COMISARIA DURANGO - C/ KURUTZIAGA 28","CNP - COMISARIA GETXO - AV. LOS CHOPOS 2"]
  },
  "9": {
    "name": "Burgos",
    "tramites": [TIE, ASILO_EXP, ASILO_SOL, NIE, AUTOREG, CARTA, CERT_UE, CERTS, INFO, UCRANIA, HUELLAS, EX_SOL, REG],
    "oficinas": ["CNP - COMISARIA BURGOS - C/ SANZ PASTOR 2","CNP - COMISARIA MIRANDA DE EBRO - AV. NAVARRA 24"]
  },
  "10": {
    "name": "Cáceres",
    "tramites": [TIE, ASILO_SOL, NIE, CARTA, CERT_UE, CERTS, CEDULA, UCRANIA_SOL, UCRANIA, PRORROGA, SOL_TARJ_ROJA, HUELLAS, EX_SOL, REG],
    "oficinas": ["CNP - COMISARIA CACERES - C/ MONTESINOS 2","CNP - COMISARIA PLASENCIA - C/ VIDRIERAS 7"]
  },
  "11": {
    "name": "Cádiz",
    "tramites": [CERT_CONC, CAMBIO_DOM, OTROS, TIE, TITULOS, ASILO_EXP, ASILO_SOL, NIE, AUTOREG, CARTA, CERT_UE, CERTS, CERT_NIE, CERT_NIE_NC, INFO, CEDULA, PRORROGA_CON, PRORROGA_SIN, UCRANIA, NIE_NO_RES, CERTS_RES_CONC, CONSULTA_NIE, DECL_ENTRADA, BREXIT, APATRIDIA, PRORROGA, RECOG_CERT, HUELLAS,
                 EX_ASIG_NIE, EX_INFO, EX_REAG, EX_SOL, REG],
    "oficinas": ["CNP - COMISARIA ALGECIRAS - C/ JOSE ANTONIO 5","CNP - COMISARIA CADIZ - C/ ANA DE VIYA 1","CNP - COMISARIA EL PUERTO DE SANTA MARIA - C/ LUIS DE REQUESENS 3","CNP - COMISARIA JEREZ DE LA FRONTERA - C/ SEVILLA 1","CNP - COMISARIA LA LINEA DE LA CONCEPCION - C/ DUQUE DE TETUÁN 17","CNP - COMISARIA SANLUCAR DE BARRAMEDA - C/ BARRAMEDA 2"]
  },
  "39": {
    "name": "Cantabria",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA SANTANDER - C/ VARGAS 51","CNP - COMISARIA TORRELAVEGA - C/ INDUSTRIA 3"]
  },
  "12": {
    "name": "Castellón",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA CASTELLON DE LA PLANA - C/ ORFEBRES 6","CNP - COMISARIA VILA-REAL - C/ MAYOR 78","CNP - COMISARIA VINAROS - C/ SANT GREGORI 2"]
  },
  "51": {
    "name": "Ceuta",
    "tramites": POL_COMUN + [EX_SOL, REG],
    "oficinas": ["CNP - COMISARIA CEUTA - C/ RECINTO SUR S/N"]
  },
  "13": {
    "name": "Ciudad Real",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA CIUDAD REAL - C/ ALARCOS 20","CNP - COMISARIA PUERTOLLANO - C/ JESUS FERNANDEZ MALO 1"]
  },
  "14": {
    "name": "Córdoba",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA CORDOBA CENTRO - C/ POETA JUAN BERNIER 2","CNP - COMISARIA LUCENA - C/ MARQUES DE COMARES 23","CNP - COMISARIA POZOBLANCO - C/ DOCTOR MANUEL COBOS 1"]
  },
  "16": {
    "name": "Cuenca",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA CUENCA - C/ FERMIN CABALLERO 8","CNP - COMISARIA TARANCÓN - C/ GOYA 4"]
  },
  "20": {
    "name": "Gipuzkoa",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA IRUN - AV. IPARRALDE 34","CNP - COMISARIA SAN SEBASTIAN - C/ EASO 8"]
  },
  "17": {
    "name": "Girona",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA BLANES - C/ ESPLANADA DEL PORT 1","CNP - COMISARIA FIGUERES - C/ AIRÀ 10","CNP - COMISARIA GIRONA - C/ BACIÀ 4","CNP - COMISARIA OLOT - C/ SANT ROCA 22"]
  },
  "18": {
    "name": "Granada",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA BAZA - C/ PEDRO POVEDA 2","CNP - COMISARIA GRANADA CENTRO - C/ DUQUESA 21","CNP - COMISARIA MOTRIL - C/ AVENIDA 1"]
  },
  "19": {
    "name": "Guadalajara",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA AZUQUECA DE HENARES - AV. CONSTITUCION 17","CNP - COMISARIA GUADALAJARA - C/ ARAGON 4"]
  },
  "21": {
    "name": "Huelva",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA ALMONTE - C/ REAL 2","CNP - COMISARIA HUELVA - C/ PLUS ULTRA 4","CNP - COMISARIA LEPE - C/ CERVANTES 2"]
  },
  "22": {
    "name": "Huesca",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA FRAGA - C/ PIRINEOS 2","CNP - COMISARIA HUESCA - C/ RICARDO DEL ARCO 6","CNP - COMISARIA MONZON - C/ SANTA BARBARA 11"]
  },
  "7": {
    "name": "Illes Balears",
    "tramites": [HUELLAS, TIE, NIE, CERTS, CEDULA, UCRANIA, TARJ_DGM, TIE_DGM, APATRIDIA,
                 EX_IBIZA_INFO, EX_IBIZA_RENOV, EX_IBIZA_SOL, EX_MALL_SOL, REG],
    "oficinas": ["CNP - COMISARIA IBIZA - C/ VICENTE CUERVO 3","CNP - COMISARIA INCA - C/ PAU 2","CNP - COMISARIA MANACOR - C/ SOLEDAD 3","CNP - COMISARIA MENORCA (MAHON) - AV. VIVES LLULL S/N","CNP - COMISARIA PALMA CENTRO - C/ RUIZ DE ALDA 8","CNP - COMISARIA PALMA SON CASTELLO - C/ GREMIO HERRERO 3"]
  },
  "23": {
    "name": "Jaén",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA ANDUJAR - C/ MUÑOZ GRANDE 7","CNP - COMISARIA JAEN - C/ ARQUITECTO BERGES 14","CNP - COMISARIA LINARES - C/ CORREDERA DE SAN MARCOS 5","CNP - COMISARIA UBEDA - C/ HORNO CONTADOR 2"]
  },
  "26": {
    "name": "La Rioja",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA CALAHORRA - C/ ERCILLA 4","CNP - COMISARIA LOGROÑO - C/ PORTALES 3"]
  },
  "35": {
    "name": "Las Palmas",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA FUERTEVENTURA (PUERTO DEL ROSARIO) - AV. PRIMERO DE MAYO 39","CNP - COMISARIA LANZAROTE (ARRECIFE) - C/ JOSE ANTONIO 36","CNP - COMISARIA LAS PALMAS CENTRO - C/ BUENOS AIRES 4","CNP - COMISARIA MASPALOMAS - AV. TIRAJANA 14","CNP - COMISARIA TELDE - C/ LEON Y CASTILLO 73"]
  },
  "24": {
    "name": "León",
    "tramites": [HUELLAS, TIE, NIE, CARTA, CERT_UE, CERTS, CEDULA, UCRANIA, TARJ_DGM, TIE_DGM, PRORROGA, AUTOREG,
                 EX_ARRAIGO, EX_FAM_REAG, EX_RENOV, EX_SOL_INIC, REG],
    "oficinas": ["CNP - COMISARIA LEON - C/ VILLA BENAVENTE 8","CNP - COMISARIA PONFERRADA - C/ ORTEGA Y GASSET 1"]
  },
  "25": {
    "name": "Lleida",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA LLEIDA - C/ DOCTOR COMBELLES 2"]
  },
  "27": {
    "name": "Lugo",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA LUGO - C/ CAMPO CASTELO 7"]
  },
  "28": {
    "name": "Madrid",
    "tramites": POL_COMUN + [ASILO_MADRID, TARJ_ROJA, ASILO_SOL, ASILO_EXP, ASILO_INFO] +
                EX_COMUN + [EX_ARRAIGO2, EX_LARGA, EX_LARGA_ACC, REG],
    "oficinas": ["COMISARIA ALCALA DE HENARES - AV. JUAN CARLOS I 8","COMISARIA ALCOBENDAS - C/ JUAN RAMON JIMENEZ 4","COMISARIA ALCORCON - C/ MOSTOLES 8","COMISARIA ARGANZUELA - C/ EMBAJADORES 116","COMISARIA CARABANCHEL - C/ GENERAL RICARDOS 110","COMISARIA COSLADA - C/ HENARES 12","COMISARIA FUENCARRAL - C/ PLASENCIA 3","COMISARIA GETAFE - AV. BLAS TELLO 3","COMISARIA HORTALEZA - C/ HERACLITO 2","COMISARIA LATINA - C/ AVIACION ESPAÑOLA S/N","COMISARIA LEGANES - C/ OBISPADO 1","COMISARIA MORATALAZ - C/ CORREGIDOR DIEGO DE VALDERRABANO 13","COMISARIA MOSTOLES - C/ NEVERO 2","COMISARIA PARLA - C/ ARCO 2","COMISARIA POZUELO DE ALARCON - C/ AGUILAS 3","COMISARIA RETIRO - C/ DOCTOR ESQUERDO 26","COMISARIA TETUAN - C/ RAMON Y CAJAL 9","COMISARIA TORREJON DE ARDOZ - C/ MAYOR 70","COMISARIA USERA - C/ PRADILLO 40","COMISARIA VALLECAS - C/ SIERRA DE ALQUIFE 5","OFICINA DE ASILO - PRADILLO 40"]
  },
  "29": {
    "name": "Málaga",
    "tramites": POL_COMUN + [TARJ_ROJA] + EX_COMUN + [EX_LARGA_ACC, REG],
    "oficinas": ["CNP - COMISARIA ANTEQUERA - C/ INFANTE DON FERNANDO 40","CNP - COMISARIA COIN - C/ REAL 80","CNP - COMISARIA ESTEPONA - AV. ESPAÑA 140","CNP - COMISARIA FUENGIROLA - C/ CAPITAN 5","CNP - COMISARIA MALAGA CENTRO - C/ MAURICIO MORO PARETO 1","CNP - COMISARIA MARBELLA - C/ JACINTO BENAVENTE S/N","CNP - COMISARIA TORREMOLINOS - AV. PALMA DE MALLORCA 12","CNP - COMISARIA VELEZ-MALAGA - C/ PINTADA 12"]
  },
  "52": {
    "name": "Melilla",
    "tramites": POL_COMUN + [EX_SOL, REG],
    "oficinas": ["CNP - COMISARIA MELILLA - C/ GENERAL POLAVIEJA 2"]
  },
  "30": {
    "name": "Murcia",
    "tramites": [TIE, ASILO_EXP, ASILO_SOL, 'POLICIA-Asignación de NIE - Murcia', 'POLICIA-Autorización de Regreso - Murcia', CERT_UE, CERTS, 'POLICIA-Expedición de Carta de Invitación - Murcia', CEDULA, SOL_APATRIDA, UCRANIA_SOL, UCRANIA, HUELLAS, EX_SOL, REG],
    "oficinas": ["CNP - COMISARIA CARTAGENA - C/ REAL 10","CNP - COMISARIA LORCA - AV. EUROPA 4","CNP - COMISARIA MOLINA DE SEGURA - AV. CONSTITUCION 56","CNP - COMISARIA MURCIA CENTRO - C/ ACISCLO DIAZ 8","CNP - COMISARIA YECLA - C/ ANTONIO NAVARRO 48"]
  },
  "31": {
    "name": "Navarra",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA PAMPLONA - C/ YANGUAS Y MIRANDA 6","CNP - COMISARIA TUDELA - AV. ZARAGOZA 38"]
  },
  "32": {
    "name": "Ourense",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA OURENSE - C/ CORONEL CEANO 7"]
  },
  "34": {
    "name": "Palencia",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA PALENCIA - C/ GENERAL AMOR 1"]
  },
  "36": {
    "name": "Pontevedra",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA PONTEVEDRA - C/ JOAQUIN COSTA 5","CNP - COMISARIA VILAGARCIA DE AROUSA - C/ TORO 1","CNP - COMISARIA VIGO CENTRO - C/ JOAQUIN YAÑEZ 6","CNP - COMISARIA VIGO COIA - C/ BARCELONA 11"]
  },
  "37": {
    "name": "Salamanca",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA SALAMANCA - C/ JULIAN SANCHEZ EL CHARRO 2"]
  },
  "38": {
    "name": "S.C. Tenerife",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - GOMERA (SAN SEBASTIAN) - AV. FRED OLSEN S/N","CNP - ICOD DE LOS VINOS - C/ OBISPO PEREZ CACERES 1","CNP - LA LAGUNA - C/ SAN AGUSTIN 30","CNP - PLAYA DE LAS AMERICAS - AV. DE LOS PUEBLOS 2","CNP - PUERTO DE LA CRUZ / LOS REALEJOS - AV. DEL CAMPO Y LLARENA 3","OUE SANTA CRUZ DE TENERIFE - C/ LA MARINA 20"]
  },
  "40": {
    "name": "Segovia",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA SEGOVIA - C/ JOSE ZORRILLA 26"]
  },
  "41": {
    "name": "Sevilla",
    "tramites": POL_COMUN + EX_COMUN + [EX_LARGA_ACC, REG],
    "oficinas": ["CNP - COMISARIA ALCALA DE GUADAIRA - C/ GARCIA MORATO 2","CNP - COMISARIA DOS HERMANAS - C/ SANTA TERESA DE JOURNET 2","CNP - COMISARIA SEVILLA CENTRO - C/ BUEN AIRE 1","CNP - COMISARIA SEVILLA NORTE - C/ RESOLANA 18","CNP - COMISARIA SEVILLA SUR - AV. KANSAS CITY S/N","CNP - COMISARIA UTRERA - C/ JOSE ARPA 7"]
  },
  "42": {
    "name": "Soria",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA SORIA - C/ NUMANCIA 1"]
  },
  "43": {
    "name": "Tarragona",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA EL VENDRELL - AV. SANTA OLIVA 6","CNP - COMISARIA REUS - C/ SANT LLORENÇ 18","CNP - COMISARIA TARRAGONA - C/ CAMI DE LA PEDRERA 2","CNP - COMISARIA TORTOSA - C/ MONTCADA 6"]
  },
  "44": {
    "name": "Teruel",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA TERUEL - C/ NUEVA 6"]
  },
  "45": {
    "name": "Toledo",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA TALAVERA DE LA REINA - AV. GREGORIO RUIZ 2","CNP - COMISARIA TOLEDO - C/ BELEN 5"]
  },
  "46": {
    "name": "Valencia",
    "tramites": POL_COMUN + [TARJ_ROJA] + EX_COMUN + [EX_LARGA, EX_LARGA_ACC, REG],
    "oficinas": ["CNP - COMISARIA ALZIRA - AV. PAIS VALENCIA 1","CNP - COMISARIA BURJASSOT - C/ ACADEMIA 8","CNP - COMISARIA GANDIA - C/ MAJOR 67","CNP - COMISARIA SAGUNTO - C/ CAMÍ REAL 177","CNP - COMISARIA TORRENT - C/ PICANYA 18","CNP - COMISARIA VALENCIA CENTRO - C/ LEPANTO 5","CNP - COMISARIA VALENCIA PATRAIX - C/ BOTANICO CAVANILLES 37","CNP - COMISARIA VALENCIA PUERTO - AV. DEL PORT 56"]
  },
  "47": {
    "name": "Valladolid",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA VALLADOLID CENTRO - C/ DOCTOR CAZALLA 4","CNP - COMISARIA VALLADOLID SUR - C/ PANADEROS 1"]
  },
  "49": {
    "name": "Zamora",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA ZAMORA - C/ BENAVENTE 2"]
  },
  "50": {
    "name": "Zaragoza",
    "tramites": POL_COMUN + EX_COMUN + [REG],
    "oficinas": ["CNP - COMISARIA CALATAYUD - C/ ARCADAS 2","CNP - COMISARIA ZARAGOZA CENTRO - C/ DOMINGO MIRAL 3","CNP - COMISARIA ZARAGOZA NORTE - AV. ALCALDE CABALLERO 2","CNP - COMISARIA ZARAGOZA SUR - C/ GOYA 20"]
  },
}
