// Provinces with their ICP codes
const PROVINCIAS = [
  { name: 'A Coruña', code: '15' },
  { name: 'Albacete', code: '02' },
  { name: 'Alicante', code: '03' },
  { name: 'Almería', code: '04' },
  { name: 'Araba', code: '01' },
  { name: 'Asturias', code: '33' },
  { name: 'Ávila', code: '05' },
  { name: 'Badajoz', code: '06' },
  { name: 'Barcelona', code: '08' },
  { name: 'Bizkaia', code: '48' },
  { name: 'Burgos', code: '09' },
  { name: 'Cáceres', code: '10' },
  { name: 'Cádiz', code: '11' },
  { name: 'Cantabria', code: '39' },
  { name: 'Castellón', code: '12' },
  { name: 'Ceuta', code: '51' },
  { name: 'Ciudad Real', code: '13' },
  { name: 'Córdoba', code: '14' },
  { name: 'Cuenca', code: '16' },
  { name: 'Gipuzkoa', code: '20' },
  { name: 'Girona', code: '17' },
  { name: 'Granada', code: '18' },
  { name: 'Guadalajara', code: '19' },
  { name: 'Huelva', code: '21' },
  { name: 'Huesca', code: '22' },
  { name: 'Illes Balears', code: '07' },
  { name: 'Jaén', code: '23' },
  { name: 'La Rioja', code: '26' },
  { name: 'Las Palmas', code: '35' },
  { name: 'León', code: '24' },
  { name: 'Lleida', code: '25' },
  { name: 'Lugo', code: '27' },
  { name: 'Madrid', code: '28' },
  { name: 'Málaga', code: '29' },
  { name: 'Melilla', code: '52' },
  { name: 'Murcia', code: '30' },
  { name: 'Navarra', code: '31' },
  { name: 'Ourense', code: '32' },
  { name: 'Palencia', code: '34' },
  { name: 'Pontevedra', code: '36' },
  { name: 'Salamanca', code: '37' },
  { name: 'S.Cruz Tenerife', code: '38' },
  { name: 'Segovia', code: '40' },
  { name: 'Sevilla', code: '41' },
  { name: 'Soria', code: '42' },
  { name: 'Tarragona', code: '43' },
  { name: 'Teruel', code: '44' },
  { name: 'Toledo', code: '45' },
  { name: 'Valencia', code: '46' },
  { name: 'Valladolid', code: '47' },
  { name: 'Zamora', code: '49' },
  { name: 'Zaragoza', code: '50' }
];

// Common tramites - these are fetched dynamically from ICP site
// These are the most common ones as fallback
const TRAMITES_COMUNES = [
  { name: 'POLICÍA-TOMA DE HUELLAS (EXPEDICIÓN DE TARJETA) INICIAL, RENOVACIÓN, DUPLICADO Y LEY 14/2013', code: 'EX07' },
  { name: 'POLICIA-CARTA DE INVITACIÓN', code: 'EX10' },
  { name: 'POLICIA-CERTIFICADO DE REGISTRO DE CIUDADANO DE LA U.E.', code: 'EX18' },
  { name: 'POLICIA - RECOGIDA DE TARJETA DE IDENTIDAD DE EXTRANJERO', code: 'EX19' },
  { name: 'POLICÍA-ASIGNACIÓN DE NIE', code: 'EX15' },
  { name: 'POLICIA-CERTIFICADOS Y ASIGNACION NIE', code: 'EX14' },
  { name: 'POLICIA - TÍTULOS DE VIAJE', code: 'EX21' },
  { name: 'POLICIA- EXPEDICIÓN/RENOVACIÓN DE DOCUMENTOS DE SOLICITANTES DE PROTECCIÓN INTERNACIONAL', code: 'EX09' },
  { name: 'POLICIA-CERTIFICADOS (DE RESIDENCIA, DE NO RESIDENTE, DE CONCORDANCIA)', code: 'EX13' },
  { name: 'POLICIA-SOLICITUD ASILO', code: 'EX03' },
  { name: 'AUTORIZACIÓN DE REGRESO', code: 'EX06' },
  { name: 'POLICIA - CERTIFICADOS CONCORDANCIA', code: 'EX20' },
  { name: 'POLICÍA-EXP.TARJETA ASOCIADA AL ACUERDO DE RETIRADA UK', code: 'EX16' },
  { name: 'POLICÍA TARJETA CONFLICTO UCRANIA', code: 'EX12' },
  { name: 'POLICÍA-ASIGNACIÓN NIE NO RESIDENTE NO COMUNITARIO', code: 'EX17' },
  { name: 'POLICÍA-CERTIFICADOS (RESIDENCIA Y CONCORDANCIA) NO COMUNITARIOS', code: 'EX11' },
  { name: 'POLICÍA-EXPEDICIÓN DE TARJETAS CUYA AUTORIZACIÓN RESUELVE LA UNIDAD DE GRANDES EMPRESAS', code: 'EX08' }
];

module.exports = { PROVINCIAS, TRAMITES_COMUNES };
