// ─── PROVINCES ────────────────────────────────────────────
const PROVINCIAS = [
  { name: 'A Coruña', code: '15' },
  { name: 'Albacete', code: '02' },
  { name: 'Alicante', code: '03' },
  { name: 'Almería', code: '04' },
  { name: 'Araba', code: '01' },
  { name: 'Asturias', code: '33' },
  { name: 'Ávila', code: '05' },
  { name: 'Badajoz', code: '06' },
  { name: 'Barcelona', code: '08' },
  { name: 'Bizkaia', code: '48' },
  { name: 'Burgos', code: '09' },
  { name: 'Cáceres', code: '10' },
  { name: 'Cádiz', code: '11' },
  { name: 'Cantabria', code: '39' },
  { name: 'Castellón', code: '12' },
  { name: 'Ceuta', code: '51' },
  { name: 'Ciudad Real', code: '13' },
  { name: 'Córdoba', code: '14' },
  { name: 'Cuenca', code: '16' },
  { name: 'Gipuzkoa', code: '20' },
  { name: 'Girona', code: '17' },
  { name: 'Granada', code: '18' },
  { name: 'Guadalajara', code: '19' },
  { name: 'Huelva', code: '21' },
  { name: 'Huesca', code: '22' },
  { name: 'Illes Balears', code: '07' },
  { name: 'Jaén', code: '23' },
  { name: 'La Rioja', code: '26' },
  { name: 'Las Palmas', code: '35' },
  { name: 'León', code: '24' },
  { name: 'Lleida', code: '25' },
  { name: 'Lugo', code: '27' },
  { name: 'Madrid', code: '28' },
  { name: 'Málaga', code: '29' },
  { name: 'Melilla', code: '52' },
  { name: 'Murcia', code: '30' },
  { name: 'Navarra', code: '31' },
  { name: 'Ourense', code: '32' },
  { name: 'Palencia', code: '34' },
  { name: 'Pontevedra', code: '36' },
  { name: 'Salamanca', code: '37' },
  { name: 'S.Cruz Tenerife', code: '38' },
  { name: 'Segovia', code: '40' },
  { name: 'Sevilla', code: '41' },
  { name: 'Soria', code: '42' },
  { name: 'Tarragona', code: '43' },
  { name: 'Teruel', code: '44' },
  { name: 'Toledo', code: '45' },
  { name: 'Valencia', code: '46' },
  { name: 'Valladolid', code: '47' },
  { name: 'Zamora', code: '49' },
  { name: 'Zaragoza', code: '50' }
];

// ─── OFICINAS POR PROVINCIA ────────────────────────────────
const OFICINAS_POR_PROVINCIA = {
  '15': [ // A Coruña
    'CNP SANTIAGO COMPOSTELA EXTRANJEROS, AVD RODRIGO DE PADRON, SN, SANTIAGO DE COMPOSTELA',
    'CNP COMISARIA A CORUÑA - LONZAS, C\\ Médico Devesa Núñez, 4, A Coruña',
    'CNP FERROL, AVENIDA DE SAN AMARO, S/N, FERROL',
    'CNP Santa Uxía de Ribeira, Av/ Das Airos, 21, Ribeira',
    'INSS - A Coruña - CAISS Nº 1, Avenida Pedro Barrié de la Maza, 18, A Coruña',
    'Oficina de Correos-A CORUÑA OP-1500010, RUA ALCALDE MANUEL CASAS, S/N, CORUÑA (A)',
    'Oficina de Correos-A CORUÑA SUC 1-1545694, AV. SARDIÑEIRA (ESTACION DE RENFE), S/N, CORUÑA (A)',
    'Oficina de Correos-A CORUÑA SUC 3-1545894, CL RODRIGO ALFREDO DE SANTIAGO, 38, CORUÑA (A)',
    'Oficina de Correos-FERROL OP-1500011, PRA. GALICIA, S/N, FERROL',
    'Oficina de Correos-SANTIAGO DE COMPOSTELA OP-1500012, RUA. DO FRANCO, 4, SANTIAGO DE COMPOSTELA',
    'Oficina de Extranjería en A Coruña, C/ Real, 53, A CORUÑA'
  ],
  '02': [ // Albacete
    'CNP ALBACETE BPEF, Buen Pastor, 1, Albacete',
    'CNP HELLIN, FORTUNATO ARIAS, 2, HELLIN',
    'CNP TARJETAS Expedición, CALDERON DE LA BARCA, 2, ALBACETE',
    'Oficina de Correos-ALBACETE OP-200010, DIONISIO GUARDIOLA, 24-26, ALBACETE',
    'TGSS - Administración 02/01, Avenida de España, 27, Albacete'
  ],
  '03': [ // Alicante
    'CNP Alcoy, Placeta Les Xiques, S/N, Alcoy',
    'CNP Alicante NIE, Ebanistería, 4-6, Alicante',
    'CNP Alicante TIE, Campo de Mirra, 6, Alicante',
    'CNP Benidorm, Apolo XI, 36, Benidorm',
    'CNP Benidorm TIE, Callosa D`Ensarria, 2, Benidorm',
    'CNP Comisaría Provincial, C/ Isabel la Católica, 25, Alicante',
    'CNP Denia, Avda Marquesado, 53, Denia',
    'CNP Elche, El Abeto, 1, Elche',
    'CNP Elda, Lamberto Amat, 26, Elda',
    'CNP Orihuela, Sol, 34, Orihuela',
    'CNP Orihuela Costa, C/ Flores, 5, Orihuela Costa',
    'CNP Torrevieja, Arquitecto Larramendi, 3, Torrevieja',
    'INSS - Alicante - CAISS Nº 1, C/ Doctor Ayela, 26-28, Alicante',
    'INSS - Alicante - CAISS Nº 3, C/ Mayor, 3, Alicante',
    'OEX ALICANTE, EBANISTERIA, 4-6, ALICANTE',
    'OEX ALTEA, SAN ISIDRO LABRADOR, 1, ALTEA'
  ],
  '04': [ // Almería
    'Almería OUE, C/ Marruecos, 1, Almeria',
    'CNP ALMERIA, AVENIDA DEL MEDITERRANEO, 201, ALMERIA',
    'CNP EL EJIDO, Avenida del bulevar, 117, El Ejido',
    'CNP ROQUETAS DE MAR, Avda. Curro Romero, 46, Roquetas de Mar',
    'INSS - Almería - CAISS Nº 1, Ctra. Sierra de Alhamilla, 170, Almería',
    'Oficina de Correos-AGUADULCE - 0472001, AV CARLOS III, 649, ROQUETAS DE MAR',
    'Oficina de Correos-ALMERIA OP-0400010, AV SAN JUAN BOSCO, 35, ALMERÍA'
  ],
  '01': [ // Araba
    'CNP Comisaría Oficina de tramitación, Olaguibel, 15, Vitoria-Gasteiz',
    'INSS - Araba - CAISS Nº 0, C/ Eduardo Dato, 36, Vitoria-Gasteiz',
    'Oficina de Correos - VITORIA-GASTEIZ OP-0100010, KAL POSTAS, 9, VITORIA-GASTEIZ',
    'Subdelegación del Gobierno en Alava, Olaguibel, 1, Vitoria-Gasteiz'
  ],
  '33': [ // Asturias
    'CNP AVILES, Río San Martín, 2, AVILES',
    'CNP GIJÓN, Plaza Máximo Gonzalez, s/n, Gijón',
    'CNP LUARCA, OLAVARRIETA, 25, LUARCA',
    'CNP OVIEDO - EXPEDICION TIE, Plaza de España, 3, Oviedo',
    'CNP OVIEDO - OTROS DOCUMENTOS, PLAZA DE ESPAÑA, 3, OVIEDO',
    'INSS - Asturias - CAISS Nº 1, C/ Doctor Alfredo Martínez, 6, Oviedo',
    'Oficina de Correos-AVILES-3340012, PZ DE LA MERCED, 4, AVILÉS',
    'Oficina de Correos-GIJON OP-3300011, PZ SEIS DE AGOSTO, S/N, GIJÓN',
    'Oficina de Correos-OVIEDO OP-3300010, CL ALONSO DE QUINTANILLA, 1, OVIEDO',
    'Oficina de Extranjería en Oviedo, Plaza de España, 3, Oviedo',
    'SOLICITUD INICIAL ASILO, OFICINA DE EXTRANJEROS, PLAZA DE ESPAÑA 3, OVIEDO'
  ],
  '05': [ // Ávila
    'CNP ÁVILA, PASEO SAN ROQUE, 34, ÁVILA',
    'INSS - Ávila - CAISS Nº 1, Plaza Claudio Sánchez Albornoz, 2, Ávila',
    'Oficina de Correos-AVILA OP-500010, PZ CATEDRAL, 2, ÁVILA',
    'Oficina de Extranjería en Ávila, Hornos Caleros, 1, Ávila'
  ],
  '06': [ // Badajoz
    'BRIGADA PROVINCIAL EXTRANJERÍA Y FRONTERAS BADAJOZ CNP, AVD. RAMÓN Y CAJAL, S/N, BADAJOZ',
    'CNP ALMENDRALEJO, Benito Pérez Galdós, S/N, ALMENDRALEJO',
    'CNP BADAJOZ, Avenida Ramón y Cajal, s/n, BADAJOZ',
    'CNP BADAJOZ CITA PREVIA POLICÍA TARJETAS, LA BOMBA, 9, BADAJOZ',
    'CNP DON BENITO, AVENIDA DE CORDOBA, S/N, DON BENITO',
    'CNP MÉRIDA BRIGADA, AVENIDA VALHONDO, 8, MERIDA-BADAJOZ',
    'CNP MÉRIDA TARJETAS, AVENIDA VALHONDO, 8, MÉRIDA-BADAJOZ',
    'CNP ZAFRA, PLAZA DEL PILAR REDONDO S/N, ZAFRA',
    'INSS - Badajoz - CAISS Nº 1, Ronda del Pilar, 15, Badajoz',
    'Oficina de Correos-BADAJOZ OP-600010, PASEO SAN FRANCISCO, S/N, BADAJOZ',
    'Oficina de Correos-MERIDA-680001, MARQUESA DE PINARES, 26, MÉRIDA',
    'OFICINA DE EXTRANJERÍA, CALLE LA BOMBA, 9, BADAJOZ'
  ],
  '11': [ // Cádiz
    'ALGECIRAS TR OFICINA EXRANJERÍA, P. Juan de Lima, 5, Algeciras',
    'CÁDIZ COMISARÍA CUERPO N. DE POLICÍA, Avenida de Andalucía, 28, Cádiz',
    'CÁDIZ OFICINA DE EXTRANJERÍA, Acacias, 2, Cádiz',
    'CNP ALGECIRAS, AV. FUERZAS ARMADAS, 6, ALGECIRAS',
    'CNP CHICLANA DE LA FRONTERA, LA FUENTE, 7, CHICLANA DE LA FRONTERA',
    'CNP JEREZ DE LA FRONTERA, Avenida de la Universidad, 10, JEREZ DE LA FRONTERA',
    'CNP LA LINEA CONCEPCIÓN, AVENIDA MENENDEZ PELAYO, S/N, LA LÍNEA DE LA CONCEPCIÓN',
    'CNP PUERTO SANTA MARIA PUERTO REAL, Carpintero de rivera, s/n, Puerto Real',
    'CNP ROTA, AVENIDA PRINCIPES DE ESPAÑA, 113, ROTA',
    'CNP SAN FERNANDO, Avenida Contitución de 1978, S/N, SAN FERNANDO',
    'INSS - Cádiz - DIRECCIÓN PROVINCIAL, Plaza de la constitución, sn, Cádiz',
    'Oficina de Correos-ALGECIRAS OP-1100011, RUIZ ZORRILLA, 42, ALGECIRAS',
    'Oficina de Correos-ALGECIRAS SUC 1. PLAZA ALTA-1108694, TARIFA, 5, ALGECIRAS',
    'Oficina de Correos-CADIZ OP-1100010, PZ TOPETE, S/N, CÁDIZ',
    'Oficina de Correos-CADIZ SUC 2. SAN JOSÉ-1105194, AVDA MARIA AUXILIADORA, 3, CÁDIZ',
    'Oficina de Correos-CADIZ SUC 3. GIBRALTAR-1115894, AV DE LA SANIDAD PÚBLICA, S/N, CÁDIZ',
    'Oficina de Correos-CHICLANA DE LA FRONTERA-1113004, JESUS NAZARENO, 4, CHICLANA DE LA FRONTERA',
    'Oficina de Correos-CHICLANA DE LA FRONTERA SUC 1-1119094, ALAMEDA DE SOLANO, 2, CHICLANA DE LA FRONTERA',
    'Oficina de Correos-EL PUERTO DE SANTA MARIA OP-1100013, PZ DEL POLVORISTA, 1, PUERTO DE SANTA MARÍA (EL)',
    'Oficina de Correos-JEREZ DE LA FRONTERA OP-1100012, CERRON, 2, JEREZ DE LA FRONTERA',
    'Oficina de Correos-JEREZ DE LA FRONTERA SUC 1. CHAPI-1105094, AV DE LA UNIVERSIDAD, S/N, JEREZ DE LA FRONTERA',
    'Oficina de Correos-JEREZ DE LA FRONTERA SUCURSAL 4. ZONA NORTE-1115594, AV DE LA ILUSTRACION, 5, JEREZ DE LA FRONTERA',
    'Oficina de Correos-LA LINEA DE LA CONCEPCION-1130001, PZ DE LA CONSTITUCION, 17, LÍNEA DE LA CONCEPCIÓN (LA)',
    'Oficina de Correos-SAN FERNANDO-1110001, REAL, 113, SAN FERNANDO',
    'Oficina de Correos-SAN FERNANDO SUC 1 ALMIRANTE LEÓN HERRERO-1112994, AV ALMIRANTE LEON HERRERO, 15, SAN FERNANDO',
    'Oficina de Correos-SANLUCAR DE BARRAMEDA-1154002, AV DEL CERRO FALON, 6, SANLÚCAR DE BARRAMEDA'
  ],
  '10': [ // Cáceres
    'CNP CACERES BPEF, Avenida Pierre de Coubertin, 13, Cáceres',
    'CNP PLASENCIA, CUEVA DE LA SERRANA, S/N, PLASENCIA',
    'CNP VALENCIA DE ALCANTARA, Canalejas, 5, VALENCIA DE ALCANTARA',
    'Oficina de Correos-CACERES OP-1000010, AVDA. ESPAÑA, 4, CÁCERES',
    'OFICINA DE EXTRANJERIA EN CACERES, C/Catedrático Antonio Silva, 7, CACERES',
    'TGSS - DIRECCIÓN PROVINCIAL, Avenida de España, 14, Cáceres'
  ],
  '09': [ // Burgos
    'CNP ARANDA DE DUERO, SAN FRANCISCO, 92, ARANDA DE DUERO',
    'CNP COMISARIA BURGOS, Avenida Castilla y León, 3, BURGOS',
    'CNP COMISARIA POLICÍA UD. DOCUMENTACIÓN, Avenida Castilla y León, 3, BURGOS',
    'CNP MIRANDA DE EBRO, ANTONIO CABEZON, 14, MIRANDA DE EBRO',
    'INSS - Burgos - CAISS Nº 1, Avenida de los Derechos Humanos, 12, Burgos',
    'Oficina de Correos-BURGOS OP-900010, PZ CONDE DE CASTRO, 1, BURGOS',
    'Oficina de Correos-BURGOS SUC 1-918094, AV CASTILLA Y LEON, 46, BURGOS',
    'Oficina de Correos-BURGOS SUC 3-918294, AV AVENIDA DE LOS DERECHOS HUMANOS, 53, BURGOS',
    'Oficina de Extranjeria en Burgos, Vitoria, 34, Burgos'
  ],
  '48': [ // Bizkaia
    'CNP BILBAO JSP del País Vasco, Gordóniz, 8, Bilbao',
    'INSS - Bizkaia - CAISS Nº 1, Avenida Sabino Arana, 3, Bilbao',
    'Oficina de Correos - ALGORTA-4899003, KAL. TERRENE, 6, ALGORTA',
    'Oficina de Correos - BARAKALDO SUC 1. CRUCES-4806694, KAL. BAKE, 34, SAN VICENTE DE BARAKALDO',
    'Oficina de Correos - BARAKALDO SUC 2_ZUAZO-4817194, ENP. LOPEZ DE AYALA, 6, SAN VICENTE DE BARAKALDO',
    'Oficina de Correos - BARAKALDO OP-4800011, KAL ARANA, 8, SAN VICENTE DE BARAKALDO',
    'Oficina de Correos - BILBAO OP-4800010, AL URQUIJO, 19, BILBAO',
    'Oficina de Correos - BILBAO SUC 1. ARENAL-4806794, KAL. VIUDA DE EPALZA, 3, BILBAO',
    'Oficina de Correos - BILBAO SUC 10. MIRIBILLA-4818094, KAL. DOCTOR ESPINOSA ORIBE, 3, BILBAO',
    'Oficina de Correos - BILBAO SUC 2. DEUSTO-4806894, ET. LEHENDAKARI AGUIRRE, 22, BILBAO',
    'Oficina de Correos - BILBAO SUC 4. TXURDINAGA-4807094, ET. JULIAN GAYARRE, 84, BILBAO',
    'Oficina de Correos - BILBAO SUC 6. LA CASILLA-4807294, PZ. LA CASILLA, Z/G, BILBAO',
    'Oficina de Correos - BILBAO SUC 7. SANTUTXU-4807394, KAL. PARTICULAR DE ALLENDE, 12, BILBAO',
    'Oficina de Correos - LAS ARENAS-AREETA-4893001, KAL. SANTA ANA, 4, ARENAS (LAS)-AREETA',
    'Oficina Extranjería Bizkaia, Barroeta Aldamar, 1, Bilbao'
  ],
  '08': [ // Barcelona
    'CNP COMISARIA BADALONA, AVDA. DELS VENTS, 9, BADALONA',
    'CNP COMISARIA CASTELLDEFELS, PLAÇA DE L`ESPERANTO, 4, CASTELLDEFELS',
    'CNP COMISARIA CERDANYOLA DEL VALLES, VERGE DE LES FEIXES, 4, CERDANYOLA DEL VALLES',
    'CNP COMISARIA CORNELLA DE LLOBREGAT, AV. SANT ILDEFONS, S/N, CORNELLA DE LLOBREGAT',
    'CNP COMISARIA EL PRAT DE LLOBREGAT, CENTRE, 4, EL PRAT DE LLOBREGAT',
    'CNP COMISARIA GRANOLLERS, RICOMA, 65, GRANOLLERS',
    'CNP COMISARIA IGUALADA, PRAT DE LA RIBA, 13, IGUALADA',
    'CNP COMISARIA LHOSPITALET DE LLOBREGAT, Rbla. Just Oliveres, 43, L`HOSPITALET DE LLOBREGAT',
    'CNP COMISARIA MANRESA, SOLER I MARCH, 5, MANRESA',
    'CNP COMISARIA MATARO, AV. GATASSA, 15, MATARO',
    'CNP COMISARIA MONTCADA I REIXAC, MAJOR, 38, MONTCADA I REIXAC',
    'CNP COMISARIA RIPOLLET, TAMARIT, 78, RIPOLLET',
    'CNP COMISARIA RUBI, TERRASSA, 16, RUBI',
    'CNP COMISARIA SABADELL, BATLLEVELL, 115, SABADELL',
    'CNP COMISARIA SANT ADRIA DEL BESOS, AV. JOAN XXIII, 2, SANT ADRIA DEL BESOS',
    'CNP COMISARIA SANT BOI DE LLOBREGAT, RIERA BASTÉ, 43, SANT BOI DE LLOBREGAT',
    'CNP COMISARIA SANT CUGAT DEL VALLES, VALLES, 1, SANT CUGAT DEL VALLES',
    'CNP COMISARIA SANT FELIU DE LLOBREGAT, CARRERETES, 9, SANT FELIU DE LLOBREGAT',
    'CNP COMISARIA SANTA COLOMA DE GRAMENET, IRLANDA, 67, SANTA COLOMA DE GRAMENET',
    'CNP COMISARIA TERRASSA, BALDRICH, 13, TERRASSA',
    'CNP COMISARIA VIC, BISBE MORGADES, 4, VIC',
    'CNP COMISARIA VILADECANS, AVDA. BALLESTER, 2, VILADECANS',
    'CNP COMISARIA VILAFRANCA DEL PENEDES, Avinguda Ronda del Mar, 109, VILAFRANCA DEL PENEDES',
    'CNP COMISARIA VILANOVA I LA GELTRU, CARRER D`OLÉRDOLA, 47, Vilanova i la Geltrú',
    'CNP GUADALAJARA, Guadalajara, 1, Barcelona',
    'CNP MALLORCA GRANADOS, MALLORCA, 213, BARCELONA',
    'CNP PSJ PLANTA BAJA, PASSEIG SANT JOAN, 189, BARCELONA',
    'CNP RAMBLA GUIPUSCOA 74, RAMBLA GUIPUSCOA, 74, BARCELONA',
    'Oficina de Correos - Sabadell Suc 3- 0840794, Bocaccio, 70, Sabadell',
    'Oficina de Correos - Sant Boi de Llobregat- 0883001, Joan Salvat-Papaseit, 33, Sant Boi de Llobregat',
    'Oficina de Correos - Sant Cugat del Vallés- 0819003, Rb Can Mora, sn, Sant Cugat del Vallés',
    'Oficina de Correos - Santa Coloma de Gramenet- 0800015, Avd Francesc Maciá, 34, Santa Coloma de Gramenet',
    'Oficina de Correos - Terrassa OP- 0800016, Pç Mossen Jacint Verdaguer, 16, Terrassa',
    'Oficina de Correos - Terrassa Suc 1- 0859394, Italia, 3, Terrassa',
    'Oficina de Correos - Terrassa Suc 3- 0883194, Ps Lluis Muncunill, 57-59, Terrassa',
    'Oficina de Correos - Terrassa Suc 4- 0883294, Pau Marsal, 36-38, Terrassa',
    'Oficina de Correos - Terrassa Suc 5- 0883394, Avd Ángel Sallent, 184-186, Terrassa',
    'Oficina de Correos - VIC- 0850001, RB Hospital, 48, VIC',
    'Oficina de Correos - Viladecans- 0884001, Sant Sebastiá, 1, Viladecans',
    'Oficina de Correos - Vilanova i la Geltrú- 0880001, Pç de les Neus, 11, Vilanova i la Geltrú',
    'TGSS - Administración 08/02, C/ Arc del Teatre, 63-65, Barcelona',
    'TGSS - DIRECCIÓN PROVINCIAL, C/ Aragón, 273-275, Barcelona',
    'TGSS - URE 08/04, Travesera de Gracia, 117, Barcelona'
  ]
};

// ─── TRAMITES COMUNES (todas las provincias) ──────────────
const TRAMITES_POLICIA_COMUNES = [
  'POLICÍA-TOMA DE HUELLAS (EXPEDICIÓN DE TARJETA) INICIAL, RENOVACIÓN, DUPLICADO Y LEY 14/2013',
  'POLICIA - RECOGIDA DE TARJETA DE IDENTIDAD DE EXTRANJERO (TIE)',
  'POLICIA- EXPEDICIÓN/RENOVACIÓN DE DOCUMENTOS DE SOLICITANTES DE ASILO',
  'POLICIA- SOLICITUD ASILO',
  'POLICIA-CARTA DE INVITACIÓN',
  'POLICIA-CERTIFICADO DE REGISTRO DE CIUDADANO DE LA U.E.',
  'POLICIA-CERTIFICADOS (DE RESIDENCIA, DE NO RESIDENCIA Y DE CONCORDANCIA)',
  'POLICIA-CERTIFICADOS Y ASIGNACION NIE',
  'POLICIA-INFORMACION DE TRÁMITES DE LA COMISARÍA DE POLICIA',
  'POLICÍA - CÉDULA DE INSCRIPCIÓN',
  'POLICÍA - UCRANIA : SOLICITUD PROTECCIÓN TEMPORAL DESPLAZADOS',
  'POLICÍA TARJETA CONFLICTO UCRANIA–ПОЛІЦІЯ -КАРТКА ДЛЯ ПЕРЕМІЩЕНИХ ОСІБ ВНАСЛІДОК КОНФЛІКТУ В УКРАЇНІ',
  'POLICIA - CERTIFICADOS CONCORDANCIA',
  'POLICIA - TÍTULOS DE VIAJE',
  'POLICÍA - SOLICITUD DE APATRIDA',
  'POLICIA-ASIGNACIÓN DE NIE',
  'POLICIA-AUTORIZACIÓN DE REGRESO',
  'POLICÍA-PRORROGA DE ESTANCIA',
  'POLICÍA-RECOGIDA DE TARJETA ROJA (PROTECCIÓN INTERNACIONAL)',
  'POLICÍA-SOLICITUD TARJETA ROJA',
  'POLICÍA - COMUNICACIÓN DE CAMBIO DE DOMICILIO',
  'ASIGNACION NIE CIUDADANOS COMUNITARIOS',
  'POLICÍA - PRORROGA DE ESTANCIA CON VISADO',
  'POLICÍA - PRORROGA DE ESTANCIA SIN VISADO',
  'POLICÍA-CONSULTA N.º DE NIE ASIGNADO',
  'POLICÍA-DECLARACIÓN DE ENTRADA',
  'POLICIA - OTROS TRÁMITES COMISARIA',
  'POLICÍA-EXPEDICIÓN/RENOVACIÓN DE DOCUMENTOS DE SOLICITUD DE APATRIDIA',
  'POLICÍA-RECOGIDA CERTIFICADO Y AUTORIZACIÓN DE REGRESO',
  'POLICIA-ASILO INFORMACION',
  'POLICÍA-CERTIFICADOS UE',
  'POLICÍA-CERTIFICADOS Y ASIGNACION NIE (NO COMUNITARIOS)',
  'POLICÍA-ASIGNACIÓN NIE NO RESIDENTE NO COMUNITARIO',
  'POLICÍA-CERTIFICADOS (RESIDENCIA Y CONCORDANCIA)',
  'POLICÍA-EXP.TARJETA ASOCIADA AL ACUERDO DE RETIRADA CIUDADANOS BRITÁNICOS Y SUS FAMILIARES (BREXIT)',
  'POLICÍA-EXPEDICIÓN DE TARJETAS CUYA AUTORIZACIÓN RESUELVE LA DIRECCIÓN GENERAL DE GESTIÓN MIGRATORIA',
  'Asignación de N.I.E.',
  'Certificado de residente o no residente',
  'CERTIFICADOS UE'
];

const TRAMITES_EXTRANJERIA_COMUNES = [
  'AUTORIZACIONES EXTRAORDINARIAS: RESIDENCIA CIR. EXC. POR RAZÓN DE ARRAIGO Y ARRAIGO EXTRAORDINARIO',
  'AUT. DE RESIDENCIA TEMPORAL POR CIRCUNS. EXCEPCIONALES POR ARRAIGO',
  'FAMILIARES DE RESIDENTES COMUNITARIOS',
  'INFORMACIÓN',
  'SOLICITUD DE AUTORIZACIONES',
  'SOLICITUD DE AUTORIZACIONES INICIALES',
  'ACCESO A 1ª AUT. DE RESIDENCIA DE LARGA DURACIÓN Y LARGA DURACIÓN UE',
  'AUTORIZACIONES DE RESIDENCIA TEMPORAL Y PERMANENTE DE FAMILIAR DE CIUDADANO DE LA UNION EUROPEA',
  'AUTORIZACIONES DE RESIDENCIA TEMPORAL POR MOTIVOS DE ARRAIGO Y OTRAS CIRCUNSTANCIAS EXCEPCIONALES',
  'AUTORIZACIONES DE TRABAJO, RENOVACIONES, PRÓRROGAS Y MODIFICACIONES',
  'RENOVACIONES, PRÓRROGAS O MODIFICACIONES',
  'Expedición de Carta de Invitación',
  'AUTORIZACIÓN DE REGRESO',
  'AUTORIZACIÓN DE RESIDENCIA DE MENORES O INCAPACITADOS NACIDOS EN ESPAÑA',
  'AUTORIZACIÓN DE RESIDENCIA DE MENORES O INCAPACITADOS NO NACIDOS EN ESPAÑA',
  'AUTORIZACIÓN DE RESIDENCIA TEMPORAL POR REAGRUPACIÓN FAMILIAR',
  'ESTANCIA POR ESTUDIOS',
  'MODIFICACIÓN de las SITUACIONES (sujeto legitimado EXTRANJERO)',
  'Recuperación de la autorización de larga duración',
  'REGISTRO',
  'RENOVACIONES DE RESIDENCIA',
  'Renovaciones, Prórrogas y Modificaciones',
  'RESIDENCIA TEMPORAL DE FAMILIARES DE PERSONAS CON NACIONALIDAD ESPAÑOLA',
  'REAGRUPACIÓN FAMILIAR',
  'RENOVACIONES DE AUT. DE RESIDENCIA y/o AUT. DE RESIDENCIA Y TRABAJO',
  'RENOVACIÓN AUTORIZACIÓN RESIDENCIA POR REAGRUPACIÓN FAMILIAR',
  'AUTORIZACIONES DE TRABAJO POR ESTUDIOS',
  'FAMILIARES DE RESIDENTES COMUNITARIOS',
  'AUTORIZACIÓN DE RESIDENCIA TEMPORAL POR CIRCUNSTANCIAS EXCEPCIONALES POR ARRAIGO',
  'AUTORIZACIÓN DE RESIDENCIA TEMPORAL POR REAGRUPACIÓN FAMILIAR',
  'ESTANCIA POR ESTUDIOS'
];

// Combine all tramites
const TRAMITES_COMUNES = [
  ...TRAMITES_EXTRANJERIA_COMUNES.map(name => ({ name, category: 'EXTRANJERÍA' })),
  ...TRAMITES_POLICIA_COMUNES.map(name => ({ name, category: 'POLICÍA NACIONAL' }))
].filter((t, i, arr) => arr.findIndex(x => x.name === t.name) === i);

module.exports = { PROVINCIAS, TRAMITES_COMUNES, OFICINAS_POR_PROVINCIA };
