"""
Static data: Spanish provinces and common trámites available
on the ICP appointment system.
"""

PROVINCES = [
    ("28", "Madrid"),
    ("08", "Barcelona"),
    ("46", "Valencia"),
    ("41", "Sevilla"),
    ("48", "Vizcaya"),
    ("50", "Zaragoza"),
    ("29", "Málaga"),
    ("07", "Baleares"),
    ("35", "Las Palmas"),
    ("38", "Santa Cruz de Tenerife"),
    ("15", "A Coruña"),
    ("47", "Valladolid"),
    ("30", "Murcia"),
    ("03", "Alicante"),
    ("33", "Asturias"),
    ("14", "Córdoba"),
    ("18", "Granada"),
    ("24", "León"),
    ("39", "Cantabria"),
    ("01", "Álava"),
    ("02", "Albacete"),
    ("04", "Almería"),
    ("05", "Ávila"),
    ("06", "Badajoz"),
    ("09", "Burgos"),
    ("10", "Cáceres"),
    ("11", "Cádiz"),
    ("12", "Castellón"),
    ("13", "Ciudad Real"),
    ("16", "Cuenca"),
    ("17", "Girona"),
    ("19", "Guadalajara"),
    ("20", "Gipuzkoa"),
    ("21", "Huelva"),
    ("22", "Huesca"),
    ("23", "Jaén"),
    ("25", "Lleida"),
    ("26", "La Rioja"),
    ("27", "Lugo"),
    ("31", "Navarra"),
    ("32", "Ourense"),
    ("34", "Palencia"),
    ("36", "Pontevedra"),
    ("37", "Salamanca"),
    ("40", "Segovia"),
    ("42", "Soria"),
    ("43", "Tarragona"),
    ("44", "Teruel"),
    ("45", "Toledo"),
    ("49", "Zamora"),
    ("51", "Ceuta"),
    ("52", "Melilla"),
]

TRAMITES = [
    ("EXTRANJERÍA", [
        ("4010", "SOLICITUD DE AUTORIZACIÓN DE REGRESO"),
        ("4031", "RENOVACIÓN DE AUTORIZACIÓN DE RESIDENCIA POR REAGRUPACIÓN FAMILIAR"),
        ("4032", "RENOVACIÓN DE AUTORIZACIÓN DE RESIDENCIA TEMPORAL Y TRABAJO POR CUENTA AJENA"),
        ("4036", "RENOVACIÓN DE AUTORIZACIÓN DE RESIDENCIA POR CIRCUNSTANCIAS EXCEPCIONALES"),
        ("4040", "SOLICITUD DE TARJETA INICIAL DE RESIDENCIA DE FAMILIAR DE CIUDADANO DE LA UE"),
        ("4041", "RENOVACIÓN DE TARJETA DE RESIDENCIA DE FAMILIAR DE CIUDADANO DE LA UE"),
        ("4500", "AUTORIZACIÓN DE RESIDENCIA Y TRABAJO. PRESENTACIÓN Y RECOGIDA."),
        ("4503", "CERTIFICADOS UE"),
        ("4508", "TARJETA DE IDENTIDAD DE EXTRANJERO - HUELLAS"),
        ("4510", "PRÓRROGA DE ESTANCIA"),
        ("4521", "EXPEDICIÓN/ RENOVACIÓN PERMISO INTERNACIONAL DE CONDUCIR"),
        ("4522", "TARJETA DE ESTUDIANTE"),
        ("4523", "RECOGIDA DE TARJETA DE IDENTIDAD DE EXTRANJERO"),
    ]),
    ("POLICÍA NACIONAL", [
        ("3001", "EXPEDICIÓN DNI"),
        ("3002", "RENOVACIÓN DNI"),
        ("3003", "EXPEDICIÓN PASAPORTE"),
        ("3004", "RENOVACIÓN PASAPORTE"),
    ]),
]
